FROM gradle:8.13.0-jdk21

WORKDIR /project

RUN apt-get update && apt-get install -yq make && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /project/code
COPY . /project/code

RUN chmod +x /project/code/app/gradlew
