.PHONY: setup build test run install run-dist clean

setup:
	sh ./gradlew clean installDist

build:
	sh ./gradlew build

test:
	sh ./gradlew test

run:
	sh ./gradlew run

install:
	sh ./gradlew installDist

run-dist:
	sh ./gradlew run

clean:
	sh ./gradlew clean
